version: '3.8'

services:
  alma-de-malta-api:
    build:
      context: .
      dockerfile: Api/AlmaDeMalta.Api/Dockerfile
    ports:
      - "5127:5127"
      - "7217:7217"
    networks:
      - app_network
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://0.0.0.0:5127
      - MongoDB__ConnectionString=mongodb://admin:admin@mongo_container:27017
      - MongoDB__DatabaseName=AlmaDeMalta
    depends_on:
      - mongo

  alma-de-malta-web:
    build:
      context: ./alma-de-malta-web
      dockerfile: Dockerfile
    ports:
      - "4200:4200" # Cambia los puertos según sea necesario
    networks:
      - app_network
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    depends_on:
      - alma-de-malta-api
      
  mongo:
    image: mongo:7
    container_name: mongo_container
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_INITDB_DATABASE}
    volumes:
      - mongo-data:/data/db
    networks:
      - app_network
    restart: unless-stopped
networks:
  app_network:
    driver: bridge

volumes:
  mongo-data:
