name: Redeploy to Heroku

on:
  workflow_dispatch:  # Solo se ejecuta manualmente

jobs:
  redeploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Git
        run: |
          git config --global user.email "felixcampoa@gmail.com"
          git config --global user.name "fcampoa"

      - name: Setup Heroku CLI
        uses: heroku/actions/setup@v1
        with:
          api-key: ${{ secrets.HEROKU_API_KEY }}

      - name: Get current branch
        id: vars
        run: echo "BRANCH=$(git rev-parse --abbrev-ref HEAD)" >> $GITHUB_ENV

      - name: Create empty commit
        run: git commit -m "Redeploy" --allow-empty

      - name: Push to Heroku
        run: |
          git remote add heroku https://git.heroku.com/tu-app-heroku.git 
          git push heroku ${{ env.BRANCH }}:main --force
